# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-19 07:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0004_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='pub_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='article',
            name='tag',
            field=models.CharField(blank=True, choices=[('dxs', '大学生'), ('lnr', '老年人'), ('xyk', '信用卡'), ('dh', '电话')], max_length=5, null=True),
        ),
    ]
