# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-19 08:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0005_auto_20161019_0747'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='watchnumber',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
