# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-20 09:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0007_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='invalid_list',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
