# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-20 10:54
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0008_invalid_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='time',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
