# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-20 10:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0009_comment_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='time',
            field=models.DateField(default='2016-10-20 10:10:02'),
        ),
    ]
