# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-21 01:44
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0011_auto_20161020_1304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='pub_date',
            field=models.DateField(default=datetime.datetime(2016, 10, 21, 1, 44, 25, 25211)),
        ),
        migrations.AlterField(
            model_name='article',
            name='tag',
            field=models.CharField(blank=True, choices=[('dxs', '大学生'), ('lnr', '老年人'), ('xyk', '信用卡'), ('sewm', '扫二维码')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='time',
            field=models.DateField(default=datetime.datetime(2016, 10, 21, 1, 44, 25, 26608)),
        ),
    ]
