# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-02 14:45
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0014_auto_20161102_1440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='pub_date',
            field=models.DateField(default=datetime.datetime(2016, 11, 2, 14, 45, 35, 946885)),
        ),
        migrations.AlterField(
            model_name='comment',
            name='time',
            field=models.DateField(default=datetime.datetime(2016, 11, 2, 14, 45, 35, 948048)),
        ),
    ]
