# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-16 00:45
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0017_auto_20161103_0204'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='headline_2',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='pub_date',
            field=models.DateField(default=datetime.datetime(2016, 11, 16, 0, 45, 24, 609454)),
        ),
        migrations.AlterField(
            model_name='comment',
            name='time',
            field=models.DateField(default=datetime.datetime(2016, 11, 16, 0, 45, 24, 613327)),
        ),
    ]
