# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-16 01:12
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0018_auto_20161116_0045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='pub_date',
            field=models.DateField(default=datetime.datetime(2016, 11, 16, 1, 12, 33, 947788)),
        ),
        migrations.AlterField(
            model_name='comment',
            name='time',
            field=models.DateField(default=datetime.datetime(2016, 11, 16, 1, 12, 33, 949095)),
        ),
    ]
