# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-17 03:21
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0020_auto_20161117_0115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='time',
            field=models.DateField(default=datetime.datetime(2016, 11, 17, 3, 21, 16, 956378)),
        ),
    ]
