# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-24 15:14
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0022_auto_20161124_1512'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='editorchoice',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='comment',
            name='time',
            field=models.DateField(default=datetime.datetime(2016, 11, 24, 15, 14, 41, 887387)),
        ),
    ]
