# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-26 06:41
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0023_auto_20161124_1514'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='cover',
            field=models.FileField(null=True, upload_to='cover_image'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='time',
            field=models.DateField(default=datetime.datetime(2016, 11, 26, 6, 41, 47, 117152)),
        ),
    ]
