# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-29 14:49
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0025_auto_20161127_0247'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice', models.CharField(choices=[('like', 'like'), ('normal', 'normal')], max_length=10)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='firstapp.Article')),
                ('voter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voted_tickets', to='firstapp.UserProfile')),
            ],
        ),
        migrations.AlterField(
            model_name='comment',
            name='time',
            field=models.DateField(default=datetime.datetime(2016, 11, 29, 14, 49, 55, 908376)),
        ),
    ]
